"""empty message

Revision ID: 951daa3babea
Revises: 676931c5038c
Create Date: 2024-09-03 22:23:04.430334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '951daa3babea'
down_revision = '676931c5038c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
